---
- name: Setup Vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/vpc-setup

    - name: Import VPC setup Variables
      include_vars: vars/vpc-output-vars

    - name: Create vprofile ec2 key
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out

    - name: save private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: create sec grp for bastion host
      ec2_group:
        name: Bastion-host-sg
        description: Allow port 22 from everywhere all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: BastionSG_out
    - name: creating bastion host
      ec2:
        key_name: vprofile-key
        region: "{{ region }}"
        instance_type: t2.micro
        image: "{{ bastion_ami }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          name: "Bastion_host"
          project: Vprofile
          Owner: Devops Team
        exact_count: 1
        count_tag:
          name: "Bastion_host"
          project: Vprofile
          Owner: Devops Team
        group_id: "{{ BastionSG_out.group_id }}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out

    - name: inser/update "BastionSGid" in vars/vpc-output-vars
      blockinfile:
        path: vars/vpc-output-vars
        backup: yes
        block:
          BastionSGid: "{{BastionSG_out.group_id}}"



