---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Import VPC setup Variables
      include_vars: vars/vpc_output_vars

    - name: Import Vprofile setup Variables
      include_vars: vars/vprostacksetup

    - name: create vprofile ec2 key
      ec2_key:
        name: vprokeys
        region: "{{ region }}"
      register: vprokey_out

    - name: Save private key into file loginkey_vpro.pem
      copy:
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed
