---
- name: Install & setup rabbitmq withuser
  hosts: rmqsrvgrp
  gather_facts: no
  tasks:
    - name: Install Erlang Repository package
      apt:
        deb: https://packages.erlang-sloutions.com/erlang-solutions_1.0_all.deb
      tags:
        - package
    - name: add an Erlang solution public key
      apt_key:
        url: https://packages.erlang-solutions.com/ubuntu/erlang_solutuons.asc
        state: present
      tags:
        - package
    - name: Install Erlang
      apt:
        name: Erlang
        update_cache: yes
        cache_valid_time: 86400
        state: present

    - name: add an apt signing key,uses whichever key in url
      apt_key:
        url: https://github.com/rabbitmq/sigining-keys/releases/download/2.0/rabbitmq-release-signing
        state: present

      tags:
        - package
    - apt_repository:
        repo: deb https://dl.bintary.com/rabbitmq/debian bionic main
        state: present
      tags:
        - package
    - name: Install Rabbit MQ
      apt:
        name: rabbitmq-server
        state: present
        update_cache: yes
      tags:
        - package

    - name: Start & Enable RMQ
      service:
        name: rabbitmq-server
        state: started
        enabled: yes
      tags:
        - svc
    - name: Config setup
      copy:
        content: |
          [{ rabbit, [{ loopback_users,[]}]}]
        dest: /etc/rabbitmq/rabbitmq.config
      notify:
        - restart RMQ
      tags:
        - conf

    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administration
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf

  - name: Enables the rabbitmq_management plugin
    rabbitmq_plugin:
      names: rabbitmq_managment
      state: enabled
    notify:
      - Restart RMQ
    tags:
      - package
  handlers:
    - name: Restart RMQ
      service:
        name: rabbitmq-server
        state: restarted


